name: build

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: openjdk:17-jdk
      options: --user root

    steps:
      - uses: actions/checkout@v2
      - uses: gradle/wrapper-validation-action@v1
      - run: ./gradlew build -S
        env:
          GITHUB_ACTOR: ${{ github.actor }}
          GITHUB_TOKEN: ${{ github.token }}
